# Generated by Django 5.1 on 2024-08-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=150)),
                ('price', models.IntegerField(max_length=4)),
            ],
        ),
    ]
